crmsystem/auth_users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from .views import MyLogoutView

app_name = "auth_users"


urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="auth_users/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "base/",
        TemplateView.as_view(template_name="auth_users/_base.html"),
        name="base",
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
]

crmsystem/crmsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("auth_users.urls")),
    path("products/", include("services_app.urls")),
    path("ads/", include("ads_company_app.urls")),
    path("leads/", include("potential_customers_app.urls")),
    path("contracts/", include("contacts_app.urls")),
    path("customers/", include("active_customers_app.urls")),
]

crmsystem/active_customers_app/models.py
from django.db import models
from potential_customers_app.models import Leads
from contacts_app.models import Contract

# Create your models here.


class Customer(models.Model):
    lead = models.OneToOneField(Leads, on_delete=models.CASCADE)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.customer_lead.first_name

crmsystem/ads_company_app/models.py
from django.db import models
from services_app.models import Services

# Create your models here.


class Advertise(models.Model):
    name = models.CharField(max_length=100, unique=True)
    ads_service = models.ForeignKey(Services, on_delete=models.CASCADE)
    promote_chanel = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return self.name

crmsystem/auth_users/models.py
from django.db import models


# Create your models here.

crmsystem/contacts_app/models.py
from django.db import models
from services_app.models import Services

# Create your models here.


class Contract(models.Model):
    name = models.CharField(max_length=50)
    provided_service = models.ForeignKey(Services, on_delete=models.CASCADE)
    file = models.FileField(upload_to="files/")
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return self.name

crmsystem/services_app/models.py
from django.db import models

# Create your models here.


class Services(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return self.name

crmsystem/auth_users/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth import authenticate, login, logout
from django.views import View
# Create your views here.


class MyLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("auth_users:login")

crmsystem/auth_users/templates/auth_users/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.services_app.view_services %}
            <li><a href="/products/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.ads_company_app.view_advertise %}
            <li><a href="/ads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.potential_customers_app.view_leads %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contacts_app.view_contract %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.active_customers_app.view_customer %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            <li><a href="/accounts/logout" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
            </a></li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

crmsystem/auth_users/templates/auth_users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>